export { default as ResourceDetails } from './details'
export { default as ResourceCarePoints } from './carepoints'
export { default as ResourceRelatedGoals } from './goals'
export { default as ResourceRelatedResources } from './related-resources'
export { default as ResourceRelatedCommunities } from './related-communities'
export { default as ResourceProvidedBy } from './related-people'
