export const TRIGGERS = {
  GOAL: {
    DETAILS: 'Goal Details',
    CORE_VALUES: 'Core Values',
    ENABLES_CAREPOINTS: 'Enables Care Points',
    CARED_FOR_BY_CAREPOINTS: 'Cared For By Care Points',
    MOTIVATES_PEOPLE: 'Motivates People',
    MOTIVATES_COMMUNITIES: 'Motivates Communities',
    RELATED_RESOURCES: 'Related Resources',
  },
  RESOURCE: {
    DETAILS: 'Resource Details',
    RELATED_GOALS: 'Related Goals',
    RELATED_CARE_POINTS: 'Related Care Points',
    RELATED_RESOURCES: 'Related Resources',
  },
  CAREPOINT: {
    DETAILS: 'Care Point Details',
    ENABLING_GOALS: 'Enabling Goals',
    GOALS_CARED_FOR: 'Goals Cared For',
    APPLIED_RESOURCES: 'Applied Resources',
  },
  COMMUNITY: {
    DETAILS: 'Community Details',
    MEMBERS: 'Members',
    GOALS: 'Goals',
    RESOURCES: 'Resources',
    RELATED_COMMUNITIES: 'Related Communities',
    COREVALUES: 'Core Values',
  },
  COREVALUE: {
    DETAILS: 'Core Value Details',
    RELATED_GOALS: 'Aligned Goals',
    RELATED_MEMBERS: 'Related Members',
    RELATED_COMMUNITIES: 'Communities Guided',
  },
  PERSON: {
    ABOUT: 'About',
    CONNECTIONS: 'Connections',
    RESOURCES: 'My Resources',
  },
  MEMBER: {
    COMMUNITIES: 'My Communities',
    GOALS: 'My Goals',
    CARE_POINTS: 'My Care Points',
    CORE_VALUES: 'My Core Values',
  },
} as const

// Define a type that includes all the values under GOAL and CAREPOINTS
export type TriggerValues =
  | (typeof TRIGGERS.GOAL)[keyof typeof TRIGGERS.GOAL]
  | (typeof TRIGGERS.RESOURCE)[keyof typeof TRIGGERS.RESOURCE]
  | (typeof TRIGGERS.CAREPOINT)[keyof typeof TRIGGERS.CAREPOINT]
  | (typeof TRIGGERS.COMMUNITY)[keyof typeof TRIGGERS.COMMUNITY]
  | (typeof TRIGGERS.COREVALUE)[keyof typeof TRIGGERS.COREVALUE]
  | (typeof TRIGGERS.PERSON)[keyof typeof TRIGGERS.PERSON]
  | (typeof TRIGGERS.MEMBER)[keyof typeof TRIGGERS.MEMBER]

export const EDIT_ROUTES = {
  GOAL: {
    DETAILS: '/details',
    CORE_VALUES: '',
    ENABLES_CAREPOINTS: '',
    CARED_FOR_BY_CAREPOINTS: '',
  },
  RESOURCE: {
    DETAILS: '/details',
    RELATED_GOALS: '',
    RELATED_COMMUNITIES: '',
    RELATED_CARE_POINTS: '',
  },
  CAREPOINTS: {
    DETAILS: '/details',
    LINKED_GOALS: '',
  },
  COMMMUNITY: {
    DETAILS: '/details',
    RELATED_COMMUNITIES: '',
    RESOURCES: '',
    GOALS: '',
    MEMBERS: '',
  },
  COREVALUE: {
    DETAILS: '/details',
    RELATED_GOALS: '',
    RELATED_MEMBERS: '',
    RELATED_COMMUNITIES: '',
  },
  PERSON: {
    ABOUT: '',
    CONNECTIONS: '',
    RESOURCES: '',
  },
  MEMBER: {
    COMMUNITIES: '',
    GOALS: '',
    CARE_POINTS: '',
    CORE_VALUES: '',
  },
} as const

export type EditRouteValues =
  (typeof EDIT_ROUTES.GOAL)[keyof typeof EDIT_ROUTES.GOAL]

export const TRIGGER_TO_ROUTE_MAP = {
  [TRIGGERS.GOAL.DETAILS]: EDIT_ROUTES.GOAL.DETAILS,
  [TRIGGERS.GOAL.CORE_VALUES]: EDIT_ROUTES.GOAL.CORE_VALUES,
  [TRIGGERS.GOAL.ENABLES_CAREPOINTS]: EDIT_ROUTES.GOAL.ENABLES_CAREPOINTS,
  [TRIGGERS.GOAL.CARED_FOR_BY_CAREPOINTS]:
    EDIT_ROUTES.GOAL.CARED_FOR_BY_CAREPOINTS,
  [TRIGGERS.CAREPOINT.DETAILS]: EDIT_ROUTES.CAREPOINTS.DETAILS,
  [TRIGGERS.CAREPOINT.ENABLING_GOALS]: EDIT_ROUTES.CAREPOINTS.LINKED_GOALS,
  [TRIGGERS.CAREPOINT.GOALS_CARED_FOR]: EDIT_ROUTES.CAREPOINTS.LINKED_GOALS,
  [TRIGGERS.RESOURCE.DETAILS]: EDIT_ROUTES.RESOURCE.DETAILS,
  [TRIGGERS.RESOURCE.RELATED_GOALS]: EDIT_ROUTES.RESOURCE.RELATED_GOALS,
  [TRIGGERS.RESOURCE.RELATED_CARE_POINTS]:
    EDIT_ROUTES.RESOURCE.RELATED_CARE_POINTS,
  [TRIGGERS.COMMUNITY.DETAILS]: EDIT_ROUTES.COMMMUNITY.DETAILS,
  [TRIGGERS.COMMUNITY.RELATED_COMMUNITIES]:
    EDIT_ROUTES.COMMMUNITY.RELATED_COMMUNITIES,
  [TRIGGERS.COMMUNITY.RESOURCES]: EDIT_ROUTES.COMMMUNITY.RESOURCES,
  [TRIGGERS.COMMUNITY.GOALS]: EDIT_ROUTES.COMMMUNITY.GOALS,
  [TRIGGERS.COMMUNITY.MEMBERS]: EDIT_ROUTES.COMMMUNITY.MEMBERS,
  [TRIGGERS.COREVALUE.DETAILS]: EDIT_ROUTES.COREVALUE.DETAILS,
  [TRIGGERS.COREVALUE.RELATED_GOALS]: EDIT_ROUTES.COREVALUE.RELATED_GOALS,
  [TRIGGERS.COREVALUE.RELATED_MEMBERS]: EDIT_ROUTES.COREVALUE.RELATED_MEMBERS,
  [TRIGGERS.COREVALUE.RELATED_COMMUNITIES]:
    EDIT_ROUTES.COREVALUE.RELATED_COMMUNITIES,
  [TRIGGERS.PERSON.ABOUT]: EDIT_ROUTES.PERSON.ABOUT,
  [TRIGGERS.PERSON.CONNECTIONS]: EDIT_ROUTES.PERSON.CONNECTIONS,
  [TRIGGERS.MEMBER.COMMUNITIES]: EDIT_ROUTES.MEMBER.COMMUNITIES,
  [TRIGGERS.PERSON.RESOURCES]: EDIT_ROUTES.PERSON.RESOURCES,
  [TRIGGERS.MEMBER.GOALS]: EDIT_ROUTES.MEMBER.GOALS,
  [TRIGGERS.MEMBER.CARE_POINTS]: EDIT_ROUTES.MEMBER.CARE_POINTS,
  [TRIGGERS.MEMBER.CORE_VALUES]: EDIT_ROUTES.MEMBER.CORE_VALUES,
}

export type EditRoutesType = typeof EDIT_ROUTES
export type GoalRoutesType = typeof EDIT_ROUTES.GOAL
export type CarePointRoutesType = typeof EDIT_ROUTES.CAREPOINTS

export type RoutesType = GoalRoutesType
