import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'
import { hashPassword, parseRequestBody, signJWT } from '../utils'
import { parseError } from '@/utils'
import { getSession, initializeDB } from '../neo4j'
import { getOrCreateMeSpace } from '@/lib/validation/space-validation'
import { createLog } from '@/lib/activity-logs/create-log'
import { hashAuthToken } from '@/lib/auth/token-hash'
import { clientIp, rateLimit } from '@/lib/auth/rate-limit'
import { INVITE_INVALID_MESSAGE } from '@/constants'

/**
 * Accept a space-invite token and provision the Person as a :User.
 *
 * The raw token is generated by addSpaceMember when a non-:User Person is
 * added to a Space and is emailed as part of the accept link. Only the
 * sha256 hash is persisted (Person.inviteTokenHash) — we re-hash the
 * URL-bound token here and look up by the indexed hash field, so a leak
 * of the Person store alone cannot be used to claim accounts.
 *
 * On success:
 *   - sets password hash
 *   - promotes Person → :User (login becomes possible)
 *   - ensures the user has exactly one MeSpace (signup invariant)
 *   - issues an access JWT + refresh token, sets them as cookies
 *   - returns the user payload and the space id to redirect into
 *
 * The token is NULL'd in the same write so it cannot be redeemed twice.
 */
const acceptInviteSchema = z.object({
  token: z.string().min(1),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  // Capped + trimmed server-side: this endpoint is unauthenticated
  // (token-gated only) and these values land on the Person node, in the
  // MeSpace name, and inside the JWT payload — an unbounded name can blow
  // the 4KB cookie limit and wedge the session.
  firstName: z.string().trim().max(100).optional(),
  lastName: z.string().trim().max(100).optional(),
})

// Single string for every "this won't work" outcome — invalid / expired /
// already-claimed / rate-limited / wrong-state — so the endpoint can't
// be used as an enumeration oracle. The shared constant lets the accept
// page recognize this exact outcome and show recovery guidance.
const INVALID_INVITE = INVITE_INVALID_MESSAGE

export async function POST(req: NextRequest) {
  // Per-IP burst limit — applied before parsing or DB I/O so a flood
  // costs only a single Redis hit per request. Fail-open if Redis is
  // unreachable (see POLICY_FAILURE_MODE). The rate-limited response
  // intentionally uses the SAME `INVALID_INVITE` shape + 400 status as
  // a normal failed redemption — the AC requires that a throttled
  // client can't differentiate "rate limited" from "bad token" via
  // status code, body shape, or response headers. We give up the
  // RFC 7231 `Retry-After` honesty for this enumeration-defense.
  const burst = await rateLimit({
    policy: 'auth-burst',
    key: `accept-invite:${clientIp(req)}`,
  })
  if (!burst.allowed) {
    return NextResponse.json({ error: INVALID_INVITE }, { status: 400 })
  }

  const parsedBody = await parseRequestBody(req)
  if (!parsedBody.ok) {
    return NextResponse.json(
      { error: parsedBody.error },
      { status: parsedBody.status }
    )
  }

  const parsed = acceptInviteSchema.safeParse(parsedBody.body)
  if (!parsed.success) {
    return NextResponse.json(
      { error: parseError(parsed.error) },
      { status: 400 }
    )
  }

  const { token, password, firstName, lastName } = parsed.data

  initializeDB()
  const session = getSession()

  // Token format is `${spaceId}.${uuid}`. The spaceId is read from the
  // token (not from a separate mutable field on Person) so stale links
  // can't misroute to a newer invite's space, and so multiple pending
  // invites for the same Person don't have to coexist on the Person.
  const dotIdx = token.indexOf('.')
  const tokenSpaceId = dotIdx > 0 ? token.slice(0, dotIdx) : null
  if (!tokenSpaceId) {
    return NextResponse.json({ error: INVALID_INVITE }, { status: 400 })
  }

  // The Person store carries only sha256(rawToken) — hash the submitted
  // raw token here so the indexed lookup can find it. Constant-time hash
  // computation also means a tampered token (any single bit flipped)
  // produces a completely different hash that won't match anything.
  const tokenHash = hashAuthToken(token)

  try {
    // 1. Validate token: must exist on a non-:User Person, must not be
    //    expired. The `NOT p:User` guard closes the post-signup hijack
    //    surface flagged by security review — once a Person becomes a
    //    User by any path (signup, prior invite accept, etc.) the
    //    token-rewrite-password path is no longer reachable.
    const tokenLookup = await session.run(
      `MATCH (p:Person {inviteTokenHash: $tokenHash})
       WHERE NOT p:User
       RETURN p.id AS personId,
              p.email AS email,
              p.inviteTokenExpires > datetime() AS isValid`,
      { tokenHash }
    )

    if (tokenLookup.records.length === 0) {
      return NextResponse.json({ error: INVALID_INVITE }, { status: 400 })
    }

    const isValid = tokenLookup.records[0].get('isValid')
    if (!isValid) {
      // Clear stale hash so the index doesn't accumulate dead entries
      await session.run(
        `MATCH (p:Person {inviteTokenHash: $tokenHash})
         SET p.inviteTokenHash = NULL,
             p.inviteTokenExpires = NULL`,
        { tokenHash }
      )
      return NextResponse.json({ error: INVALID_INVITE }, { status: 400 })
    }

    const personId = tokenLookup.records[0].get('personId') as string
    const email = tokenLookup.records[0].get('email') as string | null
    const spaceId = tokenSpaceId

    if (!email) {
      // Shouldn't happen — addSpaceMember refuses to issue tokens for
      // Persons without an email — but guard anyway. Collapsed to the
      // same response message to avoid leaking which condition failed.
      return NextResponse.json({ error: INVALID_INVITE }, { status: 400 })
    }

    // 2. Promote Person → :User. Sets the auth fields signup sets and
    //    clears the invite token in the same write so re-submission of the
    //    same link fails the existence check above.
    const hashed = await hashPassword(password)

    const provision = await session.run(
      `MATCH (p:Person {id: $personId})
       SET p:User,
           p.password = $password,
           p.firstName = coalesce($firstName, p.firstName, ''),
           p.lastName = coalesce($lastName, p.lastName, ''),
           p.updatedAt = datetime(),
           p.signupDate = coalesce(p.signupDate, datetime()),
           p.onboardingCurrentStepIndex = coalesce(p.onboardingCurrentStepIndex, 0),
           p.onboardingCompletedSteps = coalesce(p.onboardingCompletedSteps, []),
           p.onboardingIsCompleted = coalesce(p.onboardingIsCompleted, false),
           p.onboardingSkipped = coalesce(p.onboardingSkipped, false),
           p.inviteTokenHash = NULL,
           p.inviteTokenExpires = NULL
       WITH p
       // Accepting an invite makes this placeholder self-sovereign. A
       // placeholder carries (p)-[:CREATED_BY]->(importer); left intact it
       // would keep satisfying the Person PII createdBy_SOME read gate,
       // letting whoever imported them read the now-real user's full profile
       // cross-Space without consent. Shed that ownership edge on adoption.
       OPTIONAL MATCH (p)-[createdByEdge:CREATED_BY]->(:Person)
       DELETE createdByEdge
       WITH DISTINCT p
       RETURN p.id AS id, p.email AS email,
              p.firstName AS firstName, p.lastName AS lastName`,
      {
        personId,
        password: hashed,
        firstName: firstName ?? null,
        lastName: lastName ?? null,
      }
    )

    if (provision.records.length === 0) {
      return NextResponse.json(
        { error: 'Could not provision account' },
        { status: 500 }
      )
    }

    const userRecord = provision.records[0]
    const user = {
      id: userRecord.get('id') as string,
      email: userRecord.get('email') as string,
      firstName: userRecord.get('firstName') as string,
      lastName: userRecord.get('lastName') as string,
    }

    // 3. Per the kb invariant, every User has exactly one MeSpace.
    //    getOrCreateMeSpace is idempotent so re-invocation is safe if
    //    the Person already had one (e.g. dev-seeded data).
    const meSpaceName = user.firstName
      ? `${user.firstName}'s MeSpace`
      : `${user.email}'s MeSpace`
    await getOrCreateMeSpace(session, user.id, meSpaceName)

    // 4. Issue auth tokens — mirrors signup exactly (payload shape, refresh
    //    token format, cookie attributes) so downstream auth code can't
    //    tell whether the session came from signup or invite-accept.
    const token30mExp = Math.floor(Date.now() / 1000) + 60 * 30
    const accessToken = signJWT({
      user,
      expiresAt: token30mExp,
    })

    const refreshToken = `${user.id}.${crypto.randomUUID()}`
    const hashedRefreshToken = await hashPassword(refreshToken)
    await session.run(
      `MATCH (u:Person {id: $personId})
       SET u.refreshToken = $refreshToken,
           u.refreshTokenExp = $refreshTokenExp,
           u.refreshTokenRevoked = false`,
      {
        personId: user.id,
        refreshToken: hashedRefreshToken,
        refreshTokenExp: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30,
      }
    )

    const redirectTo = spaceId
      ? `/protected/dashboard/space/${spaceId}`
      : '/protected/dashboard'

    // Audit log for the accept event, attributed to the user themselves
    // (they're now :User and can be the actor on a Log node). Best-effort
    // — log failures shouldn't block a successful signup.
    createLog({
      userId: user.id,
      description: spaceId
        ? `Accepted space invite and joined space ${spaceId}`
        : 'Accepted space invite',
      spaceId: spaceId ?? undefined,
      metadata: {
        event: 'space_invite_accepted',
        ...(spaceId ? { spaceId } : {}),
      },
    }).catch((err) =>
      console.warn('Failed to log invite acceptance:', err)
    )

    const response = NextResponse.json(
      {
        message: 'Invite accepted',
        user,
        token: accessToken,
        refreshToken,
        redirectTo,
      },
      { status: 200 }
    )

    response.cookies.set('accessToken', accessToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 60 * 30,
      path: '/',
    })

    response.cookies.set('refreshToken', refreshToken, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 60 * 60 * 24 * 30,
      path: '/',
    })

    return response
  } catch (err) {
    console.error('❌ accept-invite failed:', err)
    return NextResponse.json(
      { error: 'Failed to accept invite' },
      { status: 500 }
    )
  } finally {
    await session.close()
  }
}
